CREATE TABLE shipping (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    shipping_method VARCHAR(255) NOT NULL,
    shipping_date DATE NOT NULL,
    status VARCHAR(255) NOT NULL,
    create_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    update_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    order_id BIGINT NOT NULL,
    FOREIGN KEY (order_id) REFERENCES user_orders(id) ON DELETE CASCADE
);

CREATE TABLE payments (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    payment_method VARCHAR(255) NOT NULL,
    payment_date DATE NOT NULL,
    status VARCHAR(255) NOT NULL,
    create_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    update_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    order_id BIGINT NOT NULL,
    FOREIGN KEY (order_id) REFERENCES user_orders(id) ON DELETE CASCADE
);
